on:
  push:
  pull_request:

name: Build

jobs:
  windows:
    name: 'Windows'
    runs-on: windows-latest
    steps:
    - name: Install Qt 6
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.7.2'
        host: windows

    - uses: lukka/get-cmake@latest

    - name: Restore from cache and setup vcpkg executable and data files.
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgJsonGlob: 'vcpkg.json'

    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Run CMake consuming CMakePreset.json and run vcpkg to build packages
      uses: lukka/run-cmake@v10
      with:
        configurePreset: 'ninja-multi-vcpkg'
        buildPreset: 'ninja-multi-vcpkg'
        buildPresetAdditionalArgs: "['--config Release']"

  flatpak:
    name: 'Linux/Flatpak'
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:kde-6.7
      options: --privileged
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: mossball.flatpak
        manifest-path: linux/com.github.lumiscosity.Mossball.yml
        cache-key: flatpak-builder-${{ github.sha }}
