on:
  push:
    branches: [main]
  pull_request:
name: Build Linux Flatpak
jobs:
  flatpak:
    name: "Linux: Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:kde-6.7
      options: --privileged
    steps:
    - uses: actions/checkout@v4
    submodules: recursive
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: mossball.flatpak
        manifest-path: linux/com.github.lumiscosity.Mossball.yml
        cache-key: flatpak-builder-${{ github.sha }}
